BLOG/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('posts.urls', namespace='posts')),
    
    
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup-mobile/', views.SingInMobileView.as_view(), name='signup-mobile'),
    path('signup-email/', views.SingUpEmailview.as_view(), name='signup-email'),
    path('signin-email/', views.SingUpEmailview.as_view(), name='signin-email'),
    path('signin-mobile/', views.SingInMobileView.as_view(), name='signin-mobile'),
    
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('details/<int:post_id>/<slug:post_slug>/', views.DetailsPostHomeView.as_view(),
         name='details_post'),
]

posts/models.py
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.utils import timezone
from django.db import models
from django.utils.translation import gettext_lazy as _
from accounts.models import Users
from django_jalali.db import models as jmodels
from categories.models import CategoryModel


# post managers
class PostManagers(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status_choose=PostModel.StatusPost.published)
    

class ImageModel(models.Model):
    image = models.ImageField(_('عکس'),
                              upload_to='images/post%Y/%M/%D')

class PostModel(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='posts')
    category = models.ManyToManyField(CategoryModel, 
                                 related_name='categories')
    image = models.ManyToManyField(ImageModel, related_name='images',
                                   blank=True)
    title = models.CharField(max_length=255)
    sub_title = models.CharField(_('اختصار عنوان'),
        max_length=100    
    )
    body = models.TextField(help_text='write any thing')
    slug = models.SlugField(null=True, unique=True)
    created_at = jmodels.jDateTimeField(auto_now_add=True)
    updated_at = jmodels.jDateTimeField(_('updated post'), default=timezone.now)
    
    
    class StatusPost(models.TextChoices):
        published = 'pb', _('انتشار یافته')
        reject ='rj', _('رد شده')
        
        
    status_choose = models.CharField(_('انتخاب وضعیت'), max_length=2,
                                    choices=StatusPost.choices,
                                    default=StatusPost.published)
    objects = models.Manager()
    published = PostManagers()
    
    
    def __str__(self) -> any:
        return self.title
    
    
    def get_absolute_url(self):
        return reverse_lazy("posts:details_post", args=(self.pk, self.slug))


    
    class Meta:
        verbose_name = 'مقاله و پست'
        verbose_name_plural = 'مقالات و پست ها'
        db_table = 'post'
        ordering = ('-created_at', )
        indexes = (
            models.Index(fields=['-created_at',]),
        )
    
    
# class PostImageModel(models.Model):
#     user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='posts')
#     image = models.ManyToManyField(PostModel, related_name='post_images')
    
class PostTagModel(models.Model):
    title = models.ManyToManyField(PostModel, related_name='tags')


    class Meta:
        verbose_name = 'تگ'
        verbose_name_plural = 'تگ ها'

posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from .models import PostModel, CategoryModel
from django.core.paginator import Paginator
from tickets.form import feedbackForm
from django.contrib import messages


class HomeView(View):
    templated_name = 'posts/home.html'
    form_class = feedbackForm
    def get(self, request):
        form = self.form_class()
        all_post = PostModel.published.order_by('-created_at')[:10]
        category = CategoryModel.objects.all()
        
        paginator = Paginator(all_post, 1)
        page_number = request.GET.get('page')
        all_post = paginator.get_page(page_number)
        
        context = {
            'post': all_post,
            'category': category,
            'form': form,
        }
        return render(request, self.templated_name, context)
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            first_name = cd['first_name']
            last_name = cd['last_name']
            email = cd['email']
            body = cd['body']
            form.save()
            messages.success(request, 'Thanks for your feedback!')
            return redirect('posts:home')
        return render(request, self.templated_name, {'form': form})


class DetailsPostHomeView(View):
    template_name = 'posts/post_details.html'
    def get(self, request, *args, **kwargs):
        form = get_object_or_404(PostModel.published, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return render(request, self.template_name, {'form': form})
    

posts/templates/posts/home.html
{% extends "base.html" %}

{% load static %}

{% block load_refrences %}
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
{% endblock  %}

{% block title %}
  <title>home</title>
{% endblock  %}

{% block content %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
    <!-- <a class="navbar-brand" href="#"> نیو بلاگ</a> -->
    <a href='{% url "accounts:signup-mobile" %}' class='navbar-brand'>ورود یا عضویت</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0 m-auto">
        {% for cat in category %}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html"
            >{{ cat.title_choose }}</a
          >
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</nav>
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url({% static "images/img/home-bg.jpg" %})"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          {% comment %} <h1>
              <span class="subheading">درود عزیزم</span>
          </h1> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">

      <!-- Post preview-->
      {% for posts in post %}
        <div class="post-preview">
            <a href="post.html">
            <h2 class="post-title">
                {{ posts.title }}
            </h2>
            <h3 class="post-subtitle">
                {{ posts.sub_title }}
            </h3>
            </a>
            <p class="post-meta">
            {{ posts.body }}
            </p>
            <a href=#>
                نوشته شده توسط
                {{ posts.user.first_name }} {{ posts.user.last_name }}
            </a>
            </br>
            <span>
                ایجاد شده در{{ posts.created_at | date }}
            </br>
                اخرین بروزرسانی در {{ posts.updated_at | date }}
            </span>
        </div>
        <!-- Divider-->
        <hr class="my-4" />

      {% endfor %}
      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a>
      </div>
    </div>
  </div>
</div>
<!-- Footer-->
<footer class="border-top">
  <h3 class='text-center mb-4'>send feedback</h3>
  
  {% comment %} <section class="section-feedback">
    <div class="feedback">
      <form action="">
        {% csrf_token %}
        <input type="text">
        <input type="text">
        <input type="email" name="" id="">
        <textarea name="" id="" cols="30" rows="10"></textarea>
        <input type="submit" value="send feedback">
      </form>
      <div class="image-feedback">
        <img src="{% static 'images/feedback-removebg.png' %}" alt="">
      </div>
    </div>
  </section> {% endcomment %}

  <form method='post' action=''>
    {{ form }}
    {% csrf_token %}
    <input type="submit" value="send feedback">
  </form>

  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <div class="small text-center text-muted fst-italic">
          Copyright &copy; Your Website 2023
        </div>
      </div>
    </div>
  </div>
</footer>

{% endblock %}

posts/templates/posts/post_details.html
{% extends "base.html" %}

{% block title %}
    <title>details</title>
{% endblock  %}

{% block content %}
    {{ form.body }}
{% endblock  %}